### ISSUE TITLE
Samplerate limited to 192kHz why?

### ISSUE THREAD

**Issue by DrCWO** [meldron/node-alsa-capture#1]
Hello,
the Capture is limited to 192kHz for what reason I don't know.

I just  hacked the binary caputure.node. Afer that it runs with 384kHz without any problems.

Would you please change the line
                    if (!rate_okay || (rate < 4000 || rate > 196000))
to
                    if (!rate_okay || (rate < 4000 || rate > 384000))
and publish a new release.

Thanks DrCWO

**Comment by meldron** [comment]
Hi @DrCWO,

thanks you for spotting this mistake. I must have copied some wrong upper limit.

Please submit a pull request, I will be more than happy to merge it into project.

Thanks a lot!

meldron

**Comment by DrCWO** [comment]
Hi meldorn,

thanks for your reply.

 

I have not cloned the rep but only a local copy so I cannot submit a pull at the moment.

So please change the value and submit the update by your own.

 

Thanks’ a lot

Charly

 

 

Von: meldron <notifications@github.com> 
Gesendet: Donnerstag, 17. September 2020 09:44
An: meldron/node-alsa-capture <node-alsa-capture@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [meldron/node-alsa-capture] Samplerate limited to 192kHz why? (#1)

 

Hi @DrCWO <https://github.com/DrCWO> ,

thanks you for spotting this mistake. I must have copied some wrong upper limit.

Please submit a pull request, I will be more than happy to merge it into project.

Thanks a lot!

meldron

**Comment by DrCWO** [comment]
Hi,

tried to push but get this, no idea why…

 

remote: Permission to meldron/node-alsa-capture.git denied to DrCWO.

fatal: unable to access 'https://github.com/meldron/node-alsa-capture.git/': The requested URL returned error: 403

Pushing to https://github.com/meldron/node-alsa-capture.git

 

Best Charly

 

Von: meldron <notifications@github.com> 
Gesendet: Donnerstag, 17. September 2020 09:44
An: meldron/node-alsa-capture <node-alsa-capture@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [meldron/node-alsa-capture] Samplerate limited to 192kHz why? (#1)

 

Hi @DrCWO <https://github.com/DrCWO> ,

thanks you for spotting this mistake. I must have copied some wrong upper limit.

Please submit a pull request, I will be more than happy to merge it into project.

Thanks a lot!

meldron

**Comment by meldron** [comment]
Hi @DrCWO,

to create a PR without access to the repo you first have to fork the repo, commit to your forked repo and then create a pull request in the original repo. See https://gist.github.com/Chaser324/ce0505fbed06b947d962 for a detailed explanation.

If you want to try again and become a collaborator in this repo you are welcome to do so. But if you don't want to, I can also create the fix.

Best regards,

meldron

**Comment by DrCWO** [comment]
Hope I made it ;-)

 

Von: meldron <notifications@github.com> 
Gesendet: Donnerstag, 17. September 2020 13:21
An: meldron/node-alsa-capture <node-alsa-capture@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [meldron/node-alsa-capture] Samplerate limited to 192kHz why? (#1)

 

Hi @DrCWO <https://github.com/DrCWO> ,

to create a PR without access to the repo you first have to fork the repo, commit to your forked repo and then create a pull request in the original repo. See https://gist.github.com/Chaser324/ce0505fbed06b947d962 for a detailed explanation.

If you want to try again and become a collaborator in this repo you are welcome to do so. But if you don't want to, I can also create the fix.

Best regards,

meldron

**Comment by meldron** [comment]
@DrCWO thanks a lot.

I will release a new version with your adjustments, type hints and node v10 and v12 support soon!

**Comment by meldron** [comment]
Fixed with https://github.com/meldron/node-alsa-capture/pull/3
