### ISSUE TITLE
Information about how to split data per channel from the buffer data of 'audio' event

### ISSUE THREAD

**Issue by rick-yhchen1013** [meldron/node-alsa-capture#11]
Hi,

Is it possible to retrive specific channel data from the buffer that store the data of 'audio' event of alsa-capture?

**Comment by meldron** [comment]
Hi currently the library is always using `SND_PCM_ACCESS_RW_INTERLEAVED`.  Take a look at [capture.cc#L315](https://github.com/meldron/node-alsa-capture/blob/master/capture.cc#L315). You would have to extract the channel data manually.

`SND_PCM_ACCESS_RW_INTERLEAVED` means the data is recorded like this  `LRLRLRLR` (where `L` is a sample for the left channel and `R` is a sample for the right channel)
