### ISSUE TITLE
Cannot set samplerate corretly

### ISSUE THREAD

**Issue by DrCWO** [meldron/node-alsa-capture#8]
Hi Meldorn,
I currently use the USB soundinterface: Behringer U-Phono UFO202.

If I try to open it with sample rate 44100 I get a 'rateDeviating' event telling me 48000 is used and I don't understand why.
My guess it you fall back to 'Altset 1' instead of using 'Altset 3' that offers 44100.

Help would be appreciated.
Best DrCWO

arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CODEC [USB Audio CODEC], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

cat /proc/asound/card1/stream0
Burr-Brown from TI USB Audio CODEC at usb-0000:01:00.0-1.3, full speed : USB Audio

Playback:
  Status: Stop
  Interface 1
    Altset 1
    Format: S16_LE
    Channels: 2
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 16
    Channel map: FL FR
  Interface 1
    Altset 2
    Format: S16_LE
    Channels: 1
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 16
    Channel map: MONO
  Interface 1
    Altset 3
    Format: S8
    Channels: 2
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 8
    Channel map: FL FR
  Interface 1
    Altset 4
    Format: S8
    Channels: 1
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 8
    Channel map: MONO
  Interface 1
    Altset 5
    Format: U8
    Channels: 2
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 8
    Channel map: FL FR
  Interface 1
    Altset 6
    Format: U8
    Channels: 1
    Endpoint: 2 OUT (ADAPTIVE)
    Rates: 32000, 44100, 48000
    Bits: 8
    Channel map: MONO

Capture:
  Status: Stop
  Interface 2
    Altset 1
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 48000
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 2
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 48000
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 3
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 44100
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 4
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 44100
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 5
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 32000
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 6
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 32000
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 7
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 22050
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 8
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 22050
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 9
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 16000
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 10
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 16000
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 11
    Format: S8
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 16000
    Bits: 8
    Channel map: FL FR
  Interface 2
    Altset 12
    Format: S8
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 16000
    Bits: 8
    Channel map: MONO
  Interface 2
    Altset 13
    Format: S8
    Channels: 2
    Endpoint: 4 IN (ASYNC)
    Rates: 8000
    Bits: 8
    Channel map: FL FR
  Interface 2
    Altset 14
    Format: S8
    Channels: 1
    Endpoint: 4 IN (ASYNC)
    Rates: 8000
    Bits: 8
    Channel map: MONO
  Interface 2
    Altset 15
    Format: S16_LE
    Channels: 2
    Endpoint: 4 IN (SYNC)
    Rates: 11025
    Bits: 16
    Channel map: FL FR
  Interface 2
    Altset 16
    Format: S16_LE
    Channels: 1
    Endpoint: 4 IN (SYNC)
    Rates: 11025
    Bits: 16
    Channel map: MONO
  Interface 2
    Altset 17
    Format: S8
    Channels: 2
    Endpoint: 4 IN (SYNC)
    Rates: 11025
    Bits: 8
    Channel map: FL FR
  Interface 2
    Altset 18
    Format: S8
    Channels: 1
    Endpoint: 4 IN (SYNC)
    Rates: 11025
    Bits: 8
    Channel map: MONO

**Comment by meldron** [comment]
Hi @DrCWO! Sorry for the very late response. I totally missed that issue.

I think that's a USB "problem". You have to select the correct usb profile. Have a look at https://www.draisberghof.de/usb_modeswitch/, I used that once to switch an USB audio device into another mode which supported more sample rates.

Here is how I switched the profile automatically using udev:

`/etc/udev/rules.d/audio.rules`

```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="YOUR_VENDOR_ID", ATTRS{idProduct}=="YOUR_PRODUCT_ID", PROGRAM="/bin/bash -c '/path/to/usb_modeswitch_script.sh'"
```

`/path/to/usb_modeswitch_script.sh`

```shell
#!/bin/bash
usb_modeswitch -W -vYOUR_VENDOR_ID -pYOUR_PRODUCT_ID -uCONFIG_NUM
```



I don't think this is anything, which can be achieved with ALSA, but if I am wrong, feel free to reopen.

**Comment by DrCWO** [comment]
I guess this issue was caused by the issue I reported and fixed with my issue report regarding the 176400 sample rate.
